package DBIx::Class::Migration::Tutorial::SecondMigration;

1;

=head1 NAME

DBIx::Class::Migration::Tutorial::SecondMigration - Upgrade the Database

=head1 GOAL

In this section you will change you database and learn how to create upgrade
files.  You will also create some custom fixture configurations and learn
about creating seed data.

=head1 Change you Schema

So far your L<MusicBase> application is doing fine, but some new requirements
come down.

=head1 SUMMARY

=head1 NEXT STEPS

=head1 AUTHOR

See L<DBIx::Class::Migration> for author information

=head1 COPYRIGHT & LICENSE

See L<DBIx::Class::Migration> for copyright and license information

=cut

