=head1 NAME

DBIx::Class::Migration::Script::Help::dbic_connect_attrs

=head1 SYNOPSIS

    dbic-migration install --dbic_connect_attrs on_connect_do='alter session ...'

=head1 DESCRIPTION

=over 4

=item Value

HashRef, Optional

=back

Allows you to send L<DBIx::Class> recognized attributes when connecting to a 
schema (see L<DBIx::Class::Storage::DBI/DBIx::Class-specific-connection-attributes>).

=head1 SEE ALSO

L<DBIx::Class::Migration>, L<DBIx::Class::Migration::Script>,
L<DBIx::Class::Migration::Features>, L<DBIx::Class::Migration::Tutorial>

=head1 AUTHOR

See L<DBIx::Class::Migration> for author information

=head1 COPYRIGHT & LICENSE

See L<DBIx::Class::Migration> for copyright and license information

=cut

