=head1 NAME

DBIx::Class::Migration::Script::Help::help - help command details

=head1 SYNOPSIS

  dbic-migration help

=head1 DESCRIPTION

Summary of available commands and other related Help documentation

=head1 SEE ALSO

L<DBIx::Class::Migration>, L<DBIx::Class::Migration::Script>,
L<DBIx::Class::Migration::Features>, L<DBIx::Class::Migration::Tutorial>

=head1 AUTHOR

See L<DBIx::Class::Migration> for author information

=head1 COPYRIGHT & LICENSE

See L<DBIx::Class::Migration> for copyright and license information

=cut

