=head1 NAME

DBIx::Class::Migration::Script::Help::to_version - Specify a particular target migration version

=head1 SYNOPSIS

    dbic-migration install --to_version 5

=head1 DESCRIPTION

=over 4

=item  Aliases

V

=item Value

Integer (default: Current VERSION of Schema)

=back

Used to specify which version we are going to deploy.  Defaults to whatever
is the most current version you've prepared.

Use this when you need to force install an older version, such as when you are
roundtripping prepares while fiddling with a new database version.

When required you can also populate this option with the %ENV variable
DBIC_MIGRATION_TO_VERSION.

=head1 SEE ALSO

L<DBIx::Class::Migration>, L<DBIx::Class::Migration::Script>,
L<DBIx::Class::Migration::Features>, L<DBIx::Class::Migration::Tutorial>

=head1 AUTHOR

See L<DBIx::Class::Migration> for author information

=head1 COPYRIGHT & LICENSE

See L<DBIx::Class::Migration> for copyright and license information

=cut








